name: Check PR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Lint Code
        run: yarn lint

      - name: Run Tests
        run: yarn test --coverage

      - name: Parse Coverage Summary
        id: coverage
        run: |
          TOTAL_PERCENT=$(jq -r '.total.lines.pct' < coverage/coverage-summary.json)
          echo "total_coverage=TOTAL_PERCENT" >> $TOTAL_PERCENT

      - name: Display Coverage Percentage
        run: |
          echo "Test coverage: ${{ steps.coverage.outputs.total_coverage }}%"

      - name: Check Coverage
        if: steps.coverage.outputs.total_coverage < 50
        run: exit 1
