name: Check PR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Lint Code
        run: yarn lint

      - name: Run Tests
        run: yarn test --coverage

      - name: Parse Coverage Summary
        id: coverage
        run: |
          TOTAL_PERCENT=$(jq -r '.total.lines.pct' < coverage/coverage-summary.json)
          echo "total_coverage=$TOTAL_PERCENT" >> $GITHUB_ENV

      - name: Check Coverage
        if: ${{ env.total_coverage < 50 }}
        run: |
          echo "Total coverage is ${{ env.total_coverage }}%"
          echo ${{ env.total_coverage }}
          echo "Coverage is below treshold, exiting..."
          exit 1

      - name: Check Coverage
        if: ${{ env.total_coverage >= 50 }}
        run: |
          echo "Total coverage is ${{ env.total_coverage }}%"
          echo "Coverage is meeting the requirements."
