name: Check PR

on:
  push:
    branches:
      - mainsss

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Lint Code
        run: yarn lint

      - name: Run Tests
        run: yarn test --coverage

      - name: Check Test Coverage
        run: |
          TOTAL_PERCENT=$(jq -r '.total.lines.pct' < coverage/coverage-final.json)
          echo "::set-output name=total_coverage::$TOTAL_PERCENT"
