name: Create Release and Update Version

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn install

      - name: Get current version
        id: version
        run: echo "::set-output name=current_version::$(node -p -e "require('./package.json').version")"

      - name: Parse commit message
        id: commit_message
        run: echo "::set-output name=commit_message::$(git log --format=%B -n 1 HEAD)"

      - name: Update version
        id: update_version
        run: |
          VERSION=$(node -p -e "require('./package.json').version")
          case "$VERSION" in
            *-dev) npm version patch ;;
            *) npm version minor ;;
          esac
          echo "::set-output name=new_version::$(node -p -e "require('./package.json').version")"

      - name: Commit package.json
        run: |
          git config user.name "ivan"
          git config user.email "ivan@users.noreply.github.com"
          git commit -am "chore(release): ${{ steps.update_version.outputs.new_version }}"

      - name: Create tag
        id: tag
        run: |
          git tag -a "${{ steps.update_version.outputs.new_version }}" -m "${{ steps.commit_message.outputs.commit_message }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: master
          tags: true

      - name: Create release
        uses: actions/create-release@v1
        with:
          tag_name: '${{ steps.update_version.outputs.new_version }}'
          release_name: '${{ steps.update_version.outputs.new_version }}'
          body: '${{ steps.commit_message.outputs.commit_message }}'
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
