on:
  workflow_dispatch:

name: Create Release

jobs:
  build:
    - name: create release with last commit
      uses: actions/create-release@v1
      if: steps.changelog.outputs.skipped == 'false'
      env:
        GITHUB_TOKEN: ${{ secrets.CHANGELOG_RELEASE }}
      with:
        tag_name: ${{ steps.changelog.outputs.tag }}
        release_name: ${{ steps.changelog.outputs.tag }}
        body: ${{ steps.changelog.outputs.clean_changelog }}
